apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: sms-frontend
  namespace: argocd

spec:
  project: default

  destination:
    name: khttps://kubernetes.default.svc
    namespace: sms

  source:
    repoURL: https://github.com/Ashir-Qayyum/argocd-hashicorp-vault-integration.git
    targetRevision: HEAD
    path: sms-app-helm/sms-frontend

    plugin:
      name: argocd-vault-plugin-helm

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true